tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'awscli'
brew 'fish'
brew 'git'
brew 'httpie'
brew 'hub'
brew 'jq'
brew 'terraform'

cask 'aerial'
cask 'alfred'
cask 'android-file-transfer'
cask 'authy'
cask 'cloudapp'
cask 'docker'
cask 'doxie'
cask 'firefox'
cask 'flash-ppapi'
cask 'google-chrome'
cask 'gpg-suite'
cask 'hazel'
cask 'irccloud'
cask 'iterm2'
cask 'keybase'
cask 'navicat-premium-essentials'
cask 'ngrok'
cask 'omnigraffle'
cask 'opera'
cask 'polymail'
cask 'postman'
cask 'skyfonts'
cask 'skype'
cask 'slack'
cask 'sourcetree'
cask 'spotify'
cask 'textmate'
cask 'viscosity'
cask 'vlc'
cask 'vmware-fusion'
cask 'whatsapp'

mas '1password7',     id: 1333542190
mas 'divvy',          id: 413857545
mas 'fantastical',    id: 975937182
mas 'keynote',        id: 409183694
mas 'numbers',        id: 409203825
mas 'pages',          id: 409201541
mas 'pixelmator-pro', id: 1289583905
mas 'todoist',        id: 585829637
mas 'trello',         id: 1278508951
