#!/bin/bash

GITHUB_URL="https://nodeload.github.com/danielknell/dotfiles/tar.gz/master"

if ! [ -e "${HOME}/.dotfiles" ]
then
  mkdir -p "${HOME}/.dotfiles"

  cd "${HOME}/.dotfiles"

  curl --progress-bar --location --output dotfiles.tar.gz $GITHUB_URL

  tar --strip-components=1 -zxf dotfiles.tar.gz

  rm dotfiles.tar.gz

  ./scripts/setup
else
  "${HOME}/.dotfiles/scripts/update"
fi